/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registros_univesidad;

import static java.lang.System.exit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Geo
 */
public class formulario extends javax.swing.JFrame {
 private static Connection conector; // CREAMOS UNA VARIABLE conector
 private static final String driver="com.mysql.jdbc.Driver"; // SW DEFINE EL DRIVER
 private static final String user="root"; //SE DEFINE EL USUARIO
 private static final String pass="123"; // SE DEFINE EL PASSWORD, QUE EN ESTE CASO NO SE IIENE 
 private static final String url="jdbc:mysql://localhost:3306/universidad"; // SE DEFINE LA URL DE ENLACE, 
    /**
     * Creates new form formulario
     */
    public formulario() {
        initComponents();
        panel_agregar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_datos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_finalizar = new javax.swing.JButton();
        panel_agregar = new javax.swing.JPanel();
        input_1 = new javax.swing.JTextField();
        txt_1 = new javax.swing.JLabel();
        input_3 = new javax.swing.JTextField();
        txt_2 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        txt_3 = new javax.swing.JLabel();
        txt_4 = new javax.swing.JLabel();
        input_2 = new javax.swing.JTextField();
        input_4 = new javax.swing.JTextField();
        txt_5 = new javax.swing.JLabel();
        txt_6 = new javax.swing.JLabel();
        txt_7 = new javax.swing.JLabel();
        input_6 = new javax.swing.JTextField();
        input_5 = new javax.swing.JTextField();
        input_7 = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tabla de datos para universidad");

        tabla_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cargando", "Cargando", "Cargando", "Cargando", "Cargando", "Cargando", "Cargando"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_datos);

        jLabel3.setText("Tabla a buscar:");

        txt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarActionPerformed(evt);
            }
        });

        btn_buscar.setText("Realizar busqueda");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_finalizar.setText("Finalizar proyecto");
        btn_finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finalizarActionPerformed(evt);
            }
        });

        txt_1.setText("Texto:");

        input_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_3ActionPerformed(evt);
            }
        });

        txt_2.setText("Texto:");

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        txt_3.setText("Texto:");

        txt_4.setText("Texto:");

        input_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_2ActionPerformed(evt);
            }
        });

        input_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_4ActionPerformed(evt);
            }
        });

        txt_5.setText("Texto:");

        txt_6.setText("Texto:");

        txt_7.setText("Texto:");

        input_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_6ActionPerformed(evt);
            }
        });

        input_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_5ActionPerformed(evt);
            }
        });

        input_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_agregarLayout = new javax.swing.GroupLayout(panel_agregar);
        panel_agregar.setLayout(panel_agregarLayout);
        panel_agregarLayout.setHorizontalGroup(
            panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_agregarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_1)
                    .addComponent(txt_2)
                    .addComponent(txt_3)
                    .addComponent(txt_4))
                .addGap(46, 46, 46)
                .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_agregarLayout.createSequentialGroup()
                        .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_agregarLayout.createSequentialGroup()
                                .addComponent(input_3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addComponent(txt_7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_agregarLayout.createSequentialGroup()
                                .addComponent(input_2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_agregarLayout.createSequentialGroup()
                                .addComponent(input_1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_5)))
                        .addGap(29, 29, 29)
                        .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_6, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_5, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_7, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_agregarLayout.createSequentialGroup()
                        .addComponent(input_4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_guardar)
                        .addGap(83, 83, 83))))
        );
        panel_agregarLayout.setVerticalGroup(
            panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_agregarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_1)
                    .addComponent(txt_5)
                    .addComponent(input_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_2)
                    .addComponent(input_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_6)
                    .addComponent(input_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_3)
                    .addComponent(input_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_7)
                    .addComponent(input_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_4)
                    .addComponent(input_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guardar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btn_agregar.setText("Nuevo registro");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(346, 346, 346))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar)
                        .addGap(110, 110, 110)
                        .addComponent(btn_agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_finalizar)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panel_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar)
                    .addComponent(btn_finalizar)
                    .addComponent(btn_agregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_3ActionPerformed

    private void txt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_buscarActionPerformed

    private void btn_finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finalizarActionPerformed
        // TODO add your handling code here:
           exit(0);
    }//GEN-LAST:event_btn_finalizarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
    String texto = txt_buscar.getText();
    //JOptionPane.showMessageDialog(null, "Hello World"+texto);
    conector = null; // INICIALIZAMOS LA CONEXIÓN    
    
    try{
    Class.forName(driver);
    conector = (Connection) DriverManager.getConnection(url, user, pass);
    //Statement sirve para procesar una sentencia SQL estática y obtener los resultados producidos por ella.
    Statement stmt = conector.createStatement();
    
    // Consulta a la base de datos
    String query = "SELECT * FROM "+texto+"";
    //ResultSet proporciona varios métodos para obtener los datos de columna correspondientes a un fila.
    ResultSet rs = stmt.executeQuery(query);
 
    switch(texto){
        case "asignaturas":
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Id");
    model.addColumn("Numero");
    model.addColumn("Titulo");
    model.addColumn("Programa");
    model.addColumn("Requisitos");
    tabla_datos.setModel(model);
    
    
        String [] arreglo = new String[5];
        // Mostrar resultados en una tabla
        while (rs.next()) {
            arreglo[0] = rs.getString(1);
            arreglo[1] = rs.getString(2);
            arreglo[2] = rs.getString(3);
            arreglo[3] = rs.getString(4);
            arreglo[4] = rs.getString(5);
            model.addRow(arreglo);
        }
            break;
   
        case "estudiantes":
    DefaultTableModel model1 = new DefaultTableModel();
    model1.addColumn("Id");
    model1.addColumn("Nombre");
    model1.addColumn("Programa");
    tabla_datos.setModel(model1);
    
    
        String [] arreglo1 = new String[5];
        // Mostrar resultados en una tabla
        while (rs.next()) {
            arreglo1[0] = rs.getString(1);
            arreglo1[1] = rs.getString(2);
            arreglo1[2] = rs.getString(3);
            model1.addRow(arreglo1);
        }
            break;
         
        case "ofertas":
    DefaultTableModel model2 = new DefaultTableModel();
    model2.addColumn("Id");
    model2.addColumn("Numero");
    model2.addColumn("Año");
    model2.addColumn("Semestre");
    model2.addColumn("Seleccion");
    model2.addColumn("Horarios");
    model2.addColumn("Aulas");
    tabla_datos.setModel(model2);
    
    
        String [] arreglo2 = new String[7];
        // Mostrar resultados en una tabla
        while (rs.next()) {
            arreglo2[0] = rs.getString(1);
            arreglo2[1] = rs.getString(2);
            arreglo2[2] = rs.getString(3);
            arreglo2[3] = rs.getString(4);
            arreglo2[4] = rs.getString(5);
            arreglo2[5] = rs.getString(6);
            arreglo2[6] = rs.getString(7);
            model2.addRow(arreglo2);
        }
            break;
         
        case "profesores":
    DefaultTableModel model3 = new DefaultTableModel();
    model3.addColumn("Id");
    model3.addColumn("Identificacion");
    model3.addColumn("Nombre");
    model3.addColumn("Departamento");
    tabla_datos.setModel(model3);
    
    
        String [] arreglo3 = new String[5];
        // Mostrar resultados en una tabla
        while (rs.next()) {
            arreglo3[0] = rs.getString(1);
            arreglo3[1] = rs.getString(2);
            arreglo3[2] = rs.getString(3);
            arreglo3[3] = rs.getString(4);
            model3.addRow(arreglo3);
        }
            break;
          
        default:
            JOptionPane.showMessageDialog(null, "Introduzca un nombre valido");
            break;
    }
    
    //DefaultTableModel es una clase que implementa TableModel que contiene todos 
    //los métodos necesarios para modificar datos en su interior, añadir filas o columnas y darle a cada columna el nombre que se desee.
         
    if (conector != null){
    System.out.print("CONEXIÓN ESTABLECIDA...");
    }
    }catch (ClassNotFoundException | SQLException e){
    System.out.print("ERROR DE CONEXIÓN..." + e);
    }

    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
        //Volvemos el panel que contiene nustro formulario visible
        panel_agregar.setVisible(true);
        //Ocultamos los inputs que no vamos a utilizar
        txt_5.setVisible(false);
        txt_6.setVisible(false);
        txt_7.setVisible(false);
        input_5.setVisible(false);
        input_6.setVisible(false);
        input_7.setVisible(false);
        
        //Nombramos los txt para hacer referencia a la tabla
        txt_1.setText("Numero:");
        txt_2.setText("Titulo:");
        txt_3.setText("Programa:");
        txt_4.setText("Requisito:");
 
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void input_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_2ActionPerformed

    private void input_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_4ActionPerformed

    private void input_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_6ActionPerformed

    private void input_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_5ActionPerformed

    private void input_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_7ActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
                //Obtenemos el nombre de la tabla a modificar
        String texto = txt_buscar.getText();
        System.out.print("e"+texto);
        //Obtenemos los datos de los inputs
        String numero = input_1.getText();
        String titulo = input_2.getText();
        String programa = input_3.getText();
        String requisito = input_4.getText();
        
    conector=null; // INICIALIZAMOS LA CONEXIÓN
    try{
    Class.forName(driver);
    conector= (Connection) DriverManager.getConnection(url, user, pass);
    
    //Statement sirve para procesar una sentencia SQL estática y obtener los resultados producidos por ella.
    PreparedStatement stmt;
    ResultSet rs;
    
    // Consulta a la base de datos
    stmt = conector.prepareStatement("INSERT INTO "+texto+" (numero, titulo, programa,requisitos) VALUES (?, ?, ?, ?) ");
    stmt.setString(1, numero );
    stmt.setString(2, titulo);
    stmt.setString(3, programa);
    stmt.setString(4, requisito);
    
    int res = stmt.executeUpdate();
    if(res > 0){
        JOptionPane.showMessageDialog(null, "Datos guardados con exito");
    }else{
        JOptionPane.showMessageDialog(null, "Error de conexion");
    }

 
    if (conector != null){
    System.out.print("Conexion establecida...");
    }
    }
    catch (ClassNotFoundException | SQLException e){
    System.out.print("ERROR DE CONEXIÓN..." + e);
    }
    }//GEN-LAST:event_btn_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_finalizar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JTextField input_1;
    private javax.swing.JTextField input_2;
    private javax.swing.JTextField input_3;
    private javax.swing.JTextField input_4;
    private javax.swing.JTextField input_5;
    private javax.swing.JTextField input_6;
    private javax.swing.JTextField input_7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_agregar;
    public javax.swing.JTable tabla_datos;
    private javax.swing.JLabel txt_1;
    private javax.swing.JLabel txt_2;
    private javax.swing.JLabel txt_3;
    private javax.swing.JLabel txt_4;
    private javax.swing.JLabel txt_5;
    private javax.swing.JLabel txt_6;
    private javax.swing.JLabel txt_7;
    public javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
